#! /bin/bash

docker kill gfdev
docker rm gfdev

docker run -d \
	-v /var/docker/gfdev/graphite:/opt/graphite/storage/whisper \
	-v /var/docker/gfdev/supervisor:/var/log/supervisor \
  -v /etc/localtime:/etc/localtime:ro \
  -v /etc/timezone:/etc/timezone:ro \
	-p 8080:80 \
  -p 8081:81 \
  -p 8125:8125/udp \
  -p 2003:2003/tcp \
  --name gfdev gfdev-image

#sleep 10

# start anthracite
# docker run -d \
#   --link gfdev:es -p 8082:8081 \
#   -v /etc/timezone:/etc/timezone:ro \
#   -v /etc/localtime:/etc/localtime \
#   --name anthracite anthracite-image
